version: '3.8'

services:
  dev:
    image: nestjs-api
    restart: unless-stopped
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
  prod:
    restart: unless-stopped
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
    nesjs-network: